Complete translation of 'Component Distribution'
mingrammer/network-programming-with-go pull request #18
Opened 2018-01-03 16:00 UTC by mingrammer

2018-01-04 02:45 UTC, kesuskim requested changes
삭제 할 부분은 삭제해주시면 되구, 그 외에는 고려해보시면 될 것 같습니다.

2018-01-04 02:45 UTC, kesuskim commented on architecture/component_distribution.md
> +### 예시: 분산 데이터베이스
분산형 데이터베이스 라는게 좀 더 낫지 않을까요? 형용사니깐요.

2018-01-04 02:45 UTC, kesuskim commented on architecture/component_distribution.md
>  A common labelling of components is "fat" or "thin". Fat components take up lots of memory and do complex processing. Thin components on the other hand, do little of either. There don't seem to be an
오잉... 이 부분은 삭제해야...?

2018-01-04 02:45 UTC, kesuskim commented on architecture/component_distribution.md
> +뚱뚱함과 날씬함은 상대적인 개념입니다. 브라우저는 보통 날씬한 컴포넌트에 속하는데 웹 페이지를 렌더링 해주는 일이 다이기 때문입니다.
이 부분을 이렇게 바꾸면 조금 더 좋을 것 같아요.

뚱뚱함과 날씬함은 상대적인 개념입니다. 종종 브라우저는 웹 페이지를 렌더링 해 주는 일만 하기 때문에 날씬한 컴포넌트라고 여겨지지만, 제 리눅스에서 동작하는 파이어폭스 브라우저는 제가 생각하기에 전혀 날씬하다고 할 수 없는, 500 메가바이트 가까운 메모리를 차지합니다.

2018-01-04 03:03 UTC, mingrammer commented on architecture/component_distribution.md
>  A common labelling of components is "fat" or "thin". Fat components take up lots of memory and do complex processing. Thin components on the other hand, do little of either. There don't seem to be an
어 이걸 안 삭제했네요 ㅋㅋ 삭제하겠습니다

2018-01-04 03:03 UTC, mingrammer commented on architecture/component_distribution.md
> +뚱뚱함과 날씬함은 상대적인 개념입니다. 브라우저는 보통 날씬한 컴포넌트에 속하는데 웹 페이지를 렌더링 해주는 일이 다이기 때문입니다.
@kesuskim 마지막은 그냥 빼버렸는데 찬빈님 문장처럼 이어버리면 자연스럽군요. 감사합니다 ㅎㅎ

2018-01-04 03:05 UTC, mingrammer commented on architecture/component_distribution.md
> +### 예시: 분산 데이터베이스
음 분산 데이터베이스라는 말을 더 많이 들어봐서 문제는 없을 것 같습니다. 위키 기준으로도 분산 데이터베이스라고 나와있어서 음 .. 둘 다 맞는 말이라 애매하네요 -_-

2018-01-04 04:03 UTC, kesuskim commented on architecture/component_distribution.md
> +### 예시: 분산 데이터베이스
흠.. 그렇군요. ㅋㅋ그럼 그냥 분산 데이터베이스로 하시죠... ㅎㅎ

2018-01-08 00:58 UTC, kesuskim approved these changes
Approved

2018-01-08 00:58 UTC, merged